version: "3.8"
services:
  orchestrator:
    build: ./backend
    ports:
      - "${ORCHESTRATOR_PORT:-3001}:3001"
    volumes:
      - ./backend:/app
      - ./backend/neo4j:/app/neo4j
    environment:
      - NODE_ENV=development
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    env_file:
      - .env
    depends_on:
      - neo4j
      - claude-mcp
      - gpt4-mcp
      - deepseek-mcp
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - orchestrator
    restart: unless-stopped

  neo4j:
    image: neo4j:5
    ports:
      - "${NEO4J_HTTP_PORT:-7475}:7474"
      - "${NEO4J_BOLT_PORT:-7688}:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./backend/neo4j:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_https_advertised__address=localhost:${NEO4J_HTTP_PORT:-7475}
      - NEO4J_dbms_connector_http_advertised__address=localhost:${NEO4J_HTTP_PORT:-7475}
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:${NEO4J_BOLT_PORT:-7688}
    restart: unless-stopped

  claude-mcp:
    build: ./mcp/claude
    ports:
      - "${CLAUDE_MCP_PORT:-4040}:4040"
    volumes:
      - ./mcp/claude:/app
      - /app/node_modules
    env_file:
      - .env
    restart: unless-stopped

  gpt4-mcp:
    build: ./mcp/gpt4
    ports:
      - "${GPT4_MCP_PORT:-8000}:8000"
    volumes:
      - ./mcp/gpt4:/app
    env_file:
      - .env
    restart: unless-stopped

  deepseek-mcp:
    build: ./mcp/deepseek
    ports:
      - "${DEEPSEEK_MCP_PORT:-8001}:8001"
    volumes:
      - ./mcp/deepseek:/app
    env_file:
      - .env
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
